version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  java-rest:
    build: .
    container_name: java-rest
    image: 600c3d289c17
    entrypoint: bash entrypoint.sh
    depends_on:
      - postgres
    environment:
      DB_NAME: db
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: changeme

      # this is the db password
      PGPASSWORD: changeme
    ports:
      - "80:8080"
    networks:
      - postgres
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh
#    - target/spring-boot-postgresql-0.0.1-SNAPSHOT.jar:/app/target/spring-boot-postgresql-0.0.1-SNAPSHOT.jar

networks:
  postgres:
    driver: bridge

volumes:
    postgres: